### PR TITLE
delivery_unifaun_base migration

### PR DESCRIPTION
**Pull request by iammiracle**

### CODE REVIEW

**Comment by SimonRundstedt** [comment]
Unable to install module on a Odoo 14 vanilla DB. Broken dependencies ? Parts from the odoo log attached with installation error msg.
[excerpt.log](https://github.com/vertelab/odoo-delivery/files/6376185/excerpt.log)

Regarding the deleted modules: They don't matter right now. We will add them as they are updated to 14.0 in order to not add confusion to what is migrated to Odoo14 or not.

**Review by SimonRundstedt — CHANGES_REQUESTED** [review]
Module doesn't install on a vanilla Odoo 14 installation. See comment in conversation. Will review code closer fixed.
Ask me questions if you any.

**Comment by iammiracle** [comment]
Hi @SimonRundstedt thanks for the feedback. I have updated the branch, you can check it now

**Comment by SimonRundstedt** [comment]
Read code and have made a smoke test. Found some error regarding product_qty but they are present in Odoo 8 too.

**Pull request merged**
